config/routes.rb
Rails.application.routes.draw do

  root 'site#index'

  devise_for :users do
    member do
      get :following, :followers
    end
  end

  resources :profiles

  resources :posts do
    resources :likes
    resources :comments
  end

  resources :relationships,       only: [:create, :destroy]

end

app/models/ability.rb
class Ability < ActiveRecord::Base
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    # Can READ anything
    can :read, :all

    if user.persisted? # in db, so logged in
      # Can MANAGE (create, read, update, destroy, etc.) own Post
      can :manage, Post, user: user
      can :manage, Profile, user: user
      can :manage, Comment, user:user

      # Can CREATE and DESTROY own Like
      can :create,  Like, user: user
      can :destroy, Like, user: user

    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :comments
  has_many :likes

  accepts_nested_attributes_for :user
  accepts_nested_attributes_for :comments
  accepts_nested_attributes_for :likes


  def self.search(search)
    where("title ILIKE ? OR description ILIKE ?", "%#{search}%", "%#{search}%"   )


  end

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user

  mount_uploader :image, ImageUploader

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
validates :followed_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile
  has_many :posts
  has_many :comments
  has_many :likes


  accepts_nested_attributes_for :posts
  # for following
  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  # destroying a user should destroy follow relationship
                                  dependent: :destroy
  # for followed
  has_many :passive_relationships, class_name:  "Relationship",
                                 foreign_key: "followed_id",
                                 dependent:   :destroy
  # for following
  has_many :following, through: :active_relationships, source: :followed
  # for followed
  has_many :followers, through: :passive_relationships, source: :follower

  # Follows a user.
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # Unfollows a user.
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end
# validate name column in user table
  validates :name, presence: true

  private

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?



  private

    def after_sign_in_path_for(resource)
      posts_path
    end

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :name
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
    before_action :set_comment, only: [:show, :edit, :update, :destroy]


  def create
     post = Post.find( params[:post_id] )
     @comment = Comment.new(post: post, user: current_user, comment: params[:comment] )

    if  @comment.save
      render 'create.js.erb'
    #  respond_to do |format|
    #    format.html {redirect_to post }
    #    format.js #render create.js.erb
    else
      redirect_to post_path
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

before_action :authenticate_user!

  def create
     post = Post.find( params[:post_id] )


     if like = Like.find_by( post: post, user: current_user )
       authorize! :destroy, like
       like.destroy

     else
        like = Like.new( post: post, user: current_user )
        authorize! :create, like
        like.save
     end

     redirect_to posts_path
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource


  def index
      if params[:search]
        @posts = Post.search(params[:search]).order("created_at DESC")
      else
        @posts = Post.order('created_at DESC')
      end
    end


  def show
    @post = Post.find(params[:id])
  end


 def new
    @post = Post.new
    @post.user_id = params[:user_id]
 end

 def create
    if @post.save
       redirect_to posts_path
    else
       render 'new'
    end
 end

 def edit
   @post = Post.find( params[:id] )
   authorize! :edit, post
 end

 def update
   @post = Post.find( params[:id] )
   authorize! :update, post

   if @post.update_attributes( post_params )
     redirect_to @post
   else
     render 'edit'
   end
 end

 def user
   @user = User.find( params[:user_id] )

   @posts = Post.where( user: @user ).order( created_at: :desc )

   @likes = @user.likes.joins( :post ).order( "posts.created_at DESC" )
end

private
  def post_params
      params.require( :post ).permit( :title, :description, :image, :search, :user_id, user_attributes:[:name], comments_attributes: [:comment] )
  end



end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def index
    @profiles = Profile.all
  end

  def show
    @profile = Profile.find(params[:id])
  end

  def edit
    @profile = Profile.find(params[:id])
    # authorize! :edit, profile
  end

  def update
    @profile = Profile.find( params[:id])
    # authorize! :update, profile

    if @profile.update_attributes( post_params )
      redirect_to @profile
    else
      render 'edit'
    end
  end

  def user
    @user = User.find(params[:user_id])


  end

   private

   def post_params
     params.require( :profile ).permit( :image, :expertise, :city, :country, :website, :bio )
   end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    user = User.find(params[:followed_id])
    current_user.follow(user)
    redirect_to user
  end

  def destroy
    user = Relationship.find(params[:id]).followed
    current_user.unfollow(user)
    redirect_to user
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
   :user
 end

 def resource_class
    User
 end

 def resource
   @resource ||= User.new
 end

 def devise_mapping
   @devise_mapping ||= Devise.mappings[:user]
 end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/comments/_comment.html.erb
<p><%= comment.comment %></p>
<p><em><%= link_to comment.user.name unless comment.user.blank? %> - <%= comment.created_at.strftime('%m/%d/%Y') %></em></p>
<p></p>
<hr>

app/views/comments/create.js.erb
$('#comments-list').append('<%= j render @comment %>');
  $('#comment_body').val("");

app/views/posts/_comments.html.erb
<br />
<!-- list of comments -->
<div class="callout small">
  <h5><strong> Comments: </strong></h5>
  <ul id = "comments-list">
    <hr>
    <%= render @post.comments %>
</ul>
<!-- new comment -->
  <%= form_tag post_comments_path( @post, :comment ), remote: true do %>
  <div class="form-group">
      <%= text_area_tag :comment, "", class:"form-control" %>
  </div>
  <%= submit_tag "Comment", class:"button" %>
  <% end %>
  </div>

app/views/posts/_explore.html.erb
<h1>Explore Designs</h1>


<% @posts.each do |post| %>
    <a href="<%= post_path post%>">
    <%= image_tag(post.image.thumbnail.url :class => "thumbnail inline") %> <br>
      <h2><%= post.title %></h2>
      <p><%= post.description %><p>
    </a>
<% end %>

app/views/posts/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "button" %>
<% end %>

app/views/posts/_follow_form.html.erb
<!-- should be in view where follow button is included -->
<%= render 'follow_form' %>

<!-- Not working yet - error at if line -->
<!-- send user to _follow or _unfollow partials -->
<% unless current_user?(@user)? %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/posts/_following.html.erb
<% @posts.each do |post| %>
    <a href="<%= post_path post%>">
    <%= image_tag(post.image.thumbnail.url :class => "thumbnail inline") %> <br>
      <h2><%= post.title %></h2>
      <p><%= post.description %><p>
    </a>
<% end %>

app/views/posts/_followstats.html.erb
<!-- follower/ing stats -->
<% @user ||= current_user %>
<div class="stats">

    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>

    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>
<!-- end user follower/ing stats -->

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>

    <!-- Not tested yet: append user id to post  -->
    <%= f.hidden_field :user_id, :value => @post.user_id%>

    <p>
      <%= f.label :image %> <br>
      <%= f.file_field :image %>
    </p>

    <div class="form-group">
       <%= f.label :title %>
       <%= f.text_field :title, placeholder: ". . ." %>
    </div>

    <div class="form-group">
       <%= f.label :description %>
       <%= f.text_area :description, placeholder: ". . ."   %>
    </div>


    <%= f.submit (@post.new_record? ? "Create" : "Update") %>

<% end %>

app/views/posts/_getfollowing.js.erb
$("#feed").html("<%= escape_javascript(render partial: 'following') %>");

app/views/posts/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "button" %>
<% end %>

app/views/posts/edit.html.erb
<h1> Edit Post: <%= @post.title %> </h1>

<%= render "form" %>

app/views/posts/index.html.erb
<% if can? :update, :new, :create, Post %>
<% end %>

<h1> Explore </h1>
<div class="row">
  <div class="large-12 columns">
  <% @posts.each do |post| %>

      <a href="<%= post_path post%>">

         <div class="large-4 columns" >
           <div class="small-block-grid-3">
      <%= cl_image_tag(post.image.thumbnail.url :class => "feed") %> <br>
    </div>
      <div class="small-block-grid-3">

        <strong><%= post.title %><strong> -
        <%= link_to post.user.profile do %>
          <em class="pic-username" ><%= post.user.name unless post.user.blank?   %></em>
        <% end %>
          <!-- <a href="<%= post_path post%>"> <p><%= post.description %> </a> -->

        <p>
            <% liked = Like.find_by( post: post, user: current_user ) != nil %>
            <% btn_color = liked ? "warning" : "default" %>
            <%= link_to post.likes.count.to_s + " Likes", post_likes_path( post ), method: :post, class: "button #{btn_color}", disabled: !user_signed_in? %>
        </p>
      </div>

        <!-- End Like Button -->
      </div>
      </a>
  <% end %>

</div>
</div>
</div>

app/views/posts/new.html.erb
<h1> New Post </h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<br>
<br>

<div class="row">
    <div class="small-8 columns">
      <div class="column">
        <%= image_tag(@post.image) %>
        </div>

    </div>

    <div class="small-4 columns">
    <h2 id="header-posts">My Cool Pictures</h2>
    <p id="title"><%= @post.title %></p>
    <p><%=  @post.description %></p>
    <p><% liked = Like.find_by( post: @post, user: current_user ) != nil %>
    <% btn_color = liked ? "warning" : "succes button" %>
    <%= link_to " " + @post.likes.count.to_s, post_likes_path( @post ), method: :post, class: "fi-like button #{btn_color}", disabled: !user_signed_in?  %>
  </p>
          <p><button type="button" class="success button"><i class="fi-torsos-all"></i></button><p>
            <%= link_to "Back", posts_path, class: "button",   style: "float:left;"  %>
    </div>


</div>
<div class="row">
  <div class="small-8 columns">
    <%= render 'comments' %>
  </div>
</div>

app/views/profiles/_form.html.erb
<!-- Form for adding profile info -->
<%= form_for(@profile, type: :file) do |f| %>



  <!-- Row for complete form -->
  <div class="row">
    <div class="small-12">
      <!-- Row file upload -->
      <div class="row">
        <div class="small-6 columns">
          <%= f.label :image, class: "right inline" %>
          <%= f.file_field :expertise %>
        </div>
      </div>
      <!-- Row for expertise -->
      <div class="row">
        <div class="small-6 columns">
          <%= f.label :expertise, class: "right inline" %>
          <%= f.text_field :expertise %>
        </div>
      </div>
      <!-- Row for city -->
      <div class="row">
        <div class="small-6 columns">
          <%= f.label :city %>
          <%= f.text_field :city %>
        </div>
      </div>
      <!-- Row for country -->
      <div class="row">
        <div class="small-6 columns">
          <%= f.label :country %>
          <%= f.text_field :country %>
        </div>
      </div>
      <!-- Row for country -->
      <div class="row">
        <div class="small-6 columns">
          <%= f.label :website %>
          <%= f.text_field :website %>
        </div>
      </div>
      <!-- Row for country -->
      <div class="row">
        <div class="small-6 columns">
          <%= f.label :bio %>
          <%= f.text_area :bio %>
        </div>
      </div>
      <!-- Submit/Update button -->
      <div class="row">
        <%= f.submit "Update", class: "button" %>
      </div>
    </div>
  </div> <!-- END Row for complete form -->
<% end %>

<!-- Add back button -->
<%= link_to "Back", profile_path(@profile), class: "button" %>

app/views/profiles/edit.html.erb
<%= render "form" %>

app/views/profiles/index.html.erb
<h1>Profiles</h1>

<div class="row">
  <div class="large-12 columns">
    <% @profiles.each do |profile| %>
      <div class="large-4 columns row">
        <div class="user-profiles">
          <%= image_tag profile.image.thumbnail.url if profile.image.present? %>
          <p><%= link_to profile.user.name, profile %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/profiles/show.html.erb
<!-- Should only be for own profile! -->
<%= link_to "Edit", edit_profile_path(@profile), class: "button", style: "float: right" %>

<div class="row">
  <div class="columns small-6">
    <h1><%= @profile.user.name %></h1>
    <br />
    <p><span class="profile-heading">Expertise </span><%= @profile.expertise %></p>
    <p><span class="profile-heading">City </span><%= @profile.city %></p>
    <p><span class="profile-heading">Country </span><%= @profile.country %></p>
    <p><span class="profile-heading">Website </span><%= @profile.website %></p>
    <span class="profile-heading">Bio </span><%= @profile.bio %>

  </div>
  <div class="columns small-6">
    <%= image_tag @profile.image.thumbnail.url if @profile.image.present? %>
  </div>
</div>

<br />
<br />
<br />

<!-- Hier komen de designs van de user -->
<h2>Designs</h2>
<div class="row">
  <div class="large-12 columns">
    <% @profile.user.posts.each do |post| %>
      <div class="large-4 columns">
        <div class="user-posts">
          <%= image_tag post.image.thumbnail.url if post.image.present? %>
          <p><%= post.title %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/site/index.html.erb
<div class="row home-wrapper">
  <!-- left column -->
  <div class="column large-6">
    <img src="https://d13yacurqjgara.cloudfront.net/users/215249/screenshots/2575539/octo-loader.gif" />


  </div> <!-- END left column -->

  <!-- right column -->
  <% if !user_signed_in? %>

  <div class="column large-6">
    <p><i class="fi-heart home-heart-icon"></i>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i class="fi-heart home-heart-icon"></i>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i class="fi-heart home-heart-icon"></i>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i class="fi-heart home-heart-icon"></i></p>
    <br />
    <!-- Sign Up form-->
    <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
      <%= devise_error_messages! %>

      <div><%= f.label :name, class: "sign-form-title" %><br />
      <%= f.text_field :name %></div>

      <div><%= f.label :email, class: "sign-form-title" %><br />
      <%= f.email_field :email %></div>

      <div><%= f.label :password, class: "sign-form-title" %><br />
      <%= f.password_field :password %></div>

      <div><%= f.label :password_confirmation, class: "sign-form-title" %><br />
      <%= f.password_field :password_confirmation %></div>
      <br />
      <div class="button-special-div" style="text-align:center;"><span class="center-button"><%= f.submit "Sign up", class: "button-special"  %></span></div>
    <% end %>
<% end %>
<% if user_signed_in? %>
<div class="column large-6">

<img src="https://d13yacurqjgara.cloudfront.net/users/215249/screenshots/2575539/octo-loader.gif" />

</div>
<% end %>
    </div> <!-- END Sign Up -->
  </div> <!-- END right column -->
</div>