config/routes.rb
Rails.application.routes.draw do

  root 'site#index'

  devise_for :users do
    member do
      get :following, :followers
    end
  end

  resources :profiles

  resources :posts do
    resources :likes
    resources :comments
  end

  resources :relationships,       only: [:create, :destroy]

end

app/models/ability.rb
class Ability < ActiveRecord::Base
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    # Can READ anything
    can :read, :all

    if user.persisted? # in db, so logged in
      # Can MANAGE (create, read, update, destroy, etc.) own Post
      can :manage, Post, user: user
      can :manage, Profile, user: user
      can :manage, Comment, user:user

      # Can CREATE and DESTROY own Like
      can :create,  Like, user: user
      can :destroy, Like, user: user

    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :comments
  has_many :likes

  accepts_nested_attributes_for :user
  accepts_nested_attributes_for :comments
  accepts_nested_attributes_for :likes


  def self.search(search)
    where("title ILIKE ? OR description ILIKE ?", "%#{search}%", "%#{search}%"   )


  end

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user

  mount_uploader :image, ImageUploader

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
validates :followed_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile
  has_many :posts
  has_many :comments
  has_many :likes


  accepts_nested_attributes_for :posts
  # for following
  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  # destroying a user should destroy follow relationship
                                  dependent: :destroy
  # for followed
  has_many :passive_relationships, class_name:  "Relationship",
                                 foreign_key: "followed_id",
                                 dependent:   :destroy
  # for following
  has_many :following, through: :active_relationships, source: :followed
  # for followed
  has_many :followers, through: :passive_relationships, source: :follower

  # Follows a user.
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # Unfollows a user.
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end
# validate name column in user table
  validates :name, presence: true

  private

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?



  private

    def after_sign_in_path_for(resource)
      posts_path
    end

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :name
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
    before_action :set_comment, only: [:show, :edit, :update, :destroy]


  def create
     post = Post.find( params[:post_id] )
     @comment = Comment.new(post: post, user: current_user, comment: params[:comment] )

    if  @comment.save
      render 'create.js.erb'
    #  respond_to do |format|
    #    format.html {redirect_to post }
    #    format.js #render create.js.erb
    else
      redirect_to post_path
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

before_action :authenticate_user!

  def create
     post = Post.find( params[:post_id] )


     if like = Like.find_by( post: post, user: current_user )
       authorize! :destroy, like
       like.destroy

     else
        like = Like.new( post: post, user: current_user )
        authorize! :create, like
        like.save
     end

     redirect_to posts_path
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource


  def index
      if params[:search]
        @posts = Post.search(params[:search]).order("created_at DESC")
      else
        @posts = Post.order('created_at DESC')
      end
    end


  def show
    @post = Post.find(params[:id])
  end


 def new
    @post = Post.new
    @post.user_id = params[:user_id]
 end

 def create
    if @post.save
       redirect_to posts_path
    else
       render 'new'
    end
 end

 def edit
   @post = Post.find( params[:id] )
   authorize! :edit, post
 end

 def update
   @post = Post.find( params[:id] )
   authorize! :update, post

   if @post.update_attributes( post_params )
     redirect_to @post
   else
     render 'edit'
   end
 end

 def user
   @user = User.find( params[:user_id] )

   @posts = Post.where( user: @user ).order( created_at: :desc )

   @likes = @user.likes.joins( :post ).order( "posts.created_at DESC" )
end

private
  def post_params
      params.require( :post ).permit( :title, :description, :image, :search, :user_id, user_attributes:[:name], comments_attributes: [:comment] )
  end



end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def index
    @profiles = Profile.all
  end

  def show
    @profile = Profile.find(params[:id])
  end

  def edit
    @profile = Profile.find(params[:id])
    # authorize! :edit, profile
  end

  def update
    @profile = Profile.find( params[:id])
    # authorize! :update, profile

    if @profile.update_attributes( post_params )
      redirect_to @profile
    else
      render 'edit'
    end
  end

  def user
    @user = User.find(params[:user_id])


  end

   private

   def post_params
     params.require( :profile ).permit( :image, :expertise, :city, :country, :website, :bio )
   end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
   :user
 end

 def resource_class
    User
 end

 def resource
   @resource ||= User.new
 end

 def devise_mapping
   @devise_mapping ||= Devise.mappings[:user]
 end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/layouts/_nav.html.erb
<!-- Foundation topbar -->
<div class="top-bar green-top-bar">
  <!-- Left menu -->
  <div class="top-bar-left green-top-bar">
      <ul class="menu green-top-bar">
        <h4 class="top-bar-title menu-brand green-top-bar" style="margin-left:10px;margin-top:17px;">DesignUP</h4>
          <li class="green-top-bar"><%= link_to "Home", root_path %></li>
          <li class="green-top-bar"><%= link_to "Posts", posts_path %></li>
          <li class="green-top-bar"><%= link_to "Profiles", profiles_path %></li>
          <% if user_signed_in? %>
          <li class="green-top-bar"><%= link_to "New Post", new_post_path %></li>
          <% end %>
      </ul>
  </div>
  <!-- Right menu -->
  <div class="top-bar-right green-top-bar">
    <ul class="menu green-top-bar">
      <!-- Search bar -->
      <% if user_signed_in? %>
      <li class="green-top-bar"><%= form_tag(posts_path, :method => "get", id: "search-form") do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search Posts" %></li>
      <li class="green-top-bar">    <%= submit_tag "Search", class: "succes button search-button" %>
          <% end %></li>  <% end %>
      <!-- Login, logout and username link to profile -->
      <% if !user_signed_in? %>
          <li class="green-top-bar"><%= link_to "Log In", new_user_session_path %></li>
      <% else %>
          <li class="green-top-bar"><%= link_to "Log Out", destroy_user_session_path, :method => :delete %></li>
    <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= render "layouts/nav" %>

    <div class=" column row home-wrapper">
      <%= yield %>
    </div>


  </body>
</html>